name: flutter_shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/images/shoes_1.png
    # - assets/images/shoes_2.png
    # - assets/images/shoes_3.png
    # - assets/images/shoes_4.png
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
